### PR TITLE
Filter options

### PR DESCRIPTION
**Pull request by espenhgn**
Allows setting a few klusta prm options from command line when invoking `expipe process`:
```
  --filter-order INTEGER          Butterworth filter order N. Default is N=3.
                                  For acausal filters (filter type
                                  "filtfilt"), the effective filter order is
                                  N*2
  --filter-function [filtfilt|lfilter]
                                  Filter function. The default "filtfilt"
                                  corresponds to a forward-backward filter
                                  operation, "lfilter" a forward filter. NOTE:
                                  does not affect filtering with klusta.
  --use-single-threshold [True|False]
                                  Use the same threshold across channels.
                                  Default is True
  --threshold-strong-std-factor FLOAT
                                  Strong spike detection threshold. Default is
                                  4.5
  --threshold-weak-std-factor FLOAT
```

Adds `expipe transfer` option:
```
  --override-prompts              disables yes/no prompts for automated
                                  removal of files after transfer. Default is
                                  False
```

### CODE REVIEW

**Comment by lepmik** [comment]
In stead of `--override-prompts` it is more conventional to have `-y`, `--yes`, which is what's used in the other modules as well. Do you agree to conform?

**Comment by lepmik** [comment]
Great with the filter options btw

**Comment by espenhgn** [comment]
Hi @lepmik 
I think `--override-prompts` sounds like a much less ambiguous argument than simply `-y` or `--yes`, as arguments can be supplied in an arbitrary order. But maybe you can point me to a place where your solution is used? Until then I do not agree to conform I guess. 

Anyway think that some of the option names are poorly named, like `--move` could be renamed `--remove-local` or similar, but that is better dealt with independently.

**Comment by espenhgn** [comment]
Hi @lepmik 
Maybe we should just merge this in while there is no conflict, and rather argue about this override flag later.

**Comment by lepmik** [comment]
You can see [here](https://github.com/CINPLA/expipe-dev/blob/master/expipe-plugin-cinpla/expipe_plugin_cinpla/cli_misc.py#L85) as an example on how we use a simple y, yes to override prompts elsewhere. I think it is important that the user do not have to look up every function to see how to override prompts for that specific function.

It is common to use a simple -y statement in e.g. 

`sudo apt -y install blah`
`pip -y uninstall blah`

**Comment by espenhgn** [comment]
Replaced --override-prompts with --yes option. Ok to merge?

**Comment by lepmik** [comment]
Great! Thank you for the update.

**Pull request merged**
