### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by espenhgn**
Adds `no-tracking` option to `expipe openephys process` action for experiments that do not have tracking info, plus misc fixes, as discussed in Issue #2

### CODE REVIEW

**Review by lepmik — CHANGES_REQUESTED** [review]
https://github.com/espenhgn/expipe-dev/blob/cfd3d65a8e875da39196e0693fa03da8f6326e1e/expipe-plugin-cinpla/expipe_plugin_cinpla/cli_openephys.py#L184-L205

I think this would be a better implementation
```python
if not no_convert_spikes:
    print('Converting from ".kwik" to ".exdir"')
    openephys.generate_spike_trains(exdir_path, openephys_file,
                                    source='klusta')
    print('Finished with spiketrains, you can now start manual ' +
          'clustering')
if not no_convert_lfp
    print('Filtering and downsampling raw data to LFP.')
    openephys.generate_lfp(exdir_path, openephys_file)
if not no_convert_tracking:
    print('Converting tracking from OpenEphys raw data to ".exdir"')
    openephys.generate_tracking(exdir_path, openephys_file)                    )
    if shutter_channel is not None:
        ttl_times = openephys_file.digital_in_signals[0].times[shutter_channel]
        if len(ttl_times) != 0:
            openephys_file.sync_tracking_from_events(ttl_times)
        else:
            warnings.warn(
                'No TTL events was found on IO channel {}'.format(shutter_channel)
```

**Comment by lepmik** [comment]
or the naming could be `no_spikes`, `no_lfp` and `no_tracking`

**Comment by espenhgn** [comment]
Replaced no-convert option with no_spikes, no_lfp and no_tracking options based on your code

**Comment by espenhgn** [comment]
Fixed neo-gui issues, user has to confirm delete raw files.

**Review by lepmik — APPROVED** [review]

**Pull request merged**
